[application]

[web.app]

# HTML title tag content
title = "app"

[hot_reload]
watch = ["src/"]  # Adjust path as needed

# include `assets` in web platform
[web.resource]

[web.watcher]
index_on_404 = true

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
